services:
  # ==========================================
  # MÁQUINA VIRTUAL 1 (MV1)
  # ==========================================
  broker:
    build: .
    container_name: broker_central
    # El cambio clave: se compila y luego se ejecuta con 'exec'
    command: sh -c "go build -o /tmp/app_broker broker/main.go && exec /tmp/app_broker"
    network_mode: "host"
    profiles: ["vm1"]
    stop_signal: SIGINT
    volumes:
      - .:/app

  # ==========================================
  # MÁQUINA VIRTUAL 2 (MV2)
  # ==========================================
  productor_dataclub:
    build: .
    container_name: productor_dataclub
    command: go run productor/main.go -nombre="DataClub" -catalogo="catalogo_eventos_30.json"
    network_mode: "host"
    profiles: ["vm2"]

  productor_dockers:
    build: .
    container_name: productor_dockers
    command: go run productor/main.go -nombre="Dockers Night" -catalogo="catalogo_eventos_36.json"
    network_mode: "host"
    profiles: ["vm2"]

  productor_golounge:
    build: .
    container_name: productor_golounge
    command: go run productor/main.go -nombre="GoLounge" -catalogo="catalogo_eventos_40.json"
    network_mode: "host"
    profiles: ["vm2"]

  db3:
    build: .
    container_name: nodo_db3
    command: go run nodo_db/main.go -nombre="DB3" -puerto=":50054"
    network_mode: "host"
    profiles: ["vm2"]

  # ==========================================
  # MÁQUINA VIRTUAL 3 (MV3)
  # ==========================================
  consumidor_a:
    build: .
    container_name: consumidor_a
    command: go run consumidor/main.go -nombre="Cliente_A" -pago="credito"
    network_mode: "host"
    profiles: ["vm3"]
    volumes:
      - .:/app

  consumidor_b:
    build: .
    container_name: consumidor_b
    command: go run consumidor/main.go -nombre="Cliente_B" -pago="debito"
    network_mode: "host"
    profiles: ["vm3"]
    volumes:
      - .:/app

  db2:
    build: .
    container_name: nodo_db2
    command: go run nodo_db/main.go -nombre="DB2" -puerto=":50053"
    network_mode: "host"
    profiles: ["vm3"]

  # ==========================================
  # MÁQUINA VIRTUAL 4 (MV4)
  # ==========================================
  banco:
    build: .
    container_name: banco_usm
    command: go run banco/main.go
    network_mode: "host"
    profiles: ["vm4"]

  db1:
    build: .
    container_name: nodo_db1
    command: go run nodo_db/main.go -nombre="DB1" -puerto=":50052"
    network_mode: "host"
    profiles: ["vm4"]