// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: pb/discopass.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pb_discopass_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discopass_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pb_discopass_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *RegisterRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pb_discopass_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discopass_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pb_discopass_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Event struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventoId         string                 `protobuf:"bytes,1,opt,name=evento_id,json=eventoId,proto3" json:"evento_id,omitempty"`
	Discoteca        string                 `protobuf:"bytes,2,opt,name=discoteca,proto3" json:"discoteca,omitempty"`
	NombreEvento     string                 `protobuf:"bytes,3,opt,name=nombre_evento,json=nombreEvento,proto3" json:"nombre_evento,omitempty"`
	Categoria        string                 `protobuf:"bytes,4,opt,name=categoria,proto3" json:"categoria,omitempty"`
	Comuna           string                 `protobuf:"bytes,5,opt,name=comuna,proto3" json:"comuna,omitempty"`
	Precio           int32                  `protobuf:"varint,6,opt,name=precio,proto3" json:"precio,omitempty"`
	Stock            int32                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	FechaEvento      string                 `protobuf:"bytes,8,opt,name=fecha_evento,json=fechaEvento,proto3" json:"fecha_evento,omitempty"`
	FechaPublicacion string                 `protobuf:"bytes,9,opt,name=fecha_publicacion,json=fechaPublicacion,proto3" json:"fecha_publicacion,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pb_discopass_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discopass_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pb_discopass_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetEventoId() string {
	if x != nil {
		return x.EventoId
	}
	return ""
}

func (x *Event) GetDiscoteca() string {
	if x != nil {
		return x.Discoteca
	}
	return ""
}

func (x *Event) GetNombreEvento() string {
	if x != nil {
		return x.NombreEvento
	}
	return ""
}

func (x *Event) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

func (x *Event) GetComuna() string {
	if x != nil {
		return x.Comuna
	}
	return ""
}

func (x *Event) GetPrecio() int32 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *Event) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Event) GetFechaEvento() string {
	if x != nil {
		return x.FechaEvento
	}
	return ""
}

func (x *Event) GetFechaPublicacion() string {
	if x != nil {
		return x.FechaPublicacion
	}
	return ""
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_pb_discopass_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discopass_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_pb_discopass_proto_rawDescGZIP(), []int{3}
}

func (x *PublishResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PublishResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_pb_discopass_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discopass_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_pb_discopass_proto_rawDescGZIP(), []int{4}
}

type EventList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventList) Reset() {
	*x = EventList{}
	mi := &file_pb_discopass_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventList) ProtoMessage() {}

func (x *EventList) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discopass_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventList.ProtoReflect.Descriptor instead.
func (*EventList) Descriptor() ([]byte, []int) {
	return file_pb_discopass_proto_rawDescGZIP(), []int{5}
}

func (x *EventList) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type BuyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsuarioId     string                 `protobuf:"bytes,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	EventoId      string                 `protobuf:"bytes,2,opt,name=evento_id,json=eventoId,proto3" json:"evento_id,omitempty"`
	MedioPago     string                 `protobuf:"bytes,3,opt,name=medio_pago,json=medioPago,proto3" json:"medio_pago,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyRequest) Reset() {
	*x = BuyRequest{}
	mi := &file_pb_discopass_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyRequest) ProtoMessage() {}

func (x *BuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discopass_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyRequest.ProtoReflect.Descriptor instead.
func (*BuyRequest) Descriptor() ([]byte, []int) {
	return file_pb_discopass_proto_rawDescGZIP(), []int{6}
}

func (x *BuyRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *BuyRequest) GetEventoId() string {
	if x != nil {
		return x.EventoId
	}
	return ""
}

func (x *BuyRequest) GetMedioPago() string {
	if x != nil {
		return x.MedioPago
	}
	return ""
}

type BuyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyResponse) Reset() {
	*x = BuyResponse{}
	mi := &file_pb_discopass_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyResponse) ProtoMessage() {}

func (x *BuyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discopass_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyResponse.ProtoReflect.Descriptor instead.
func (*BuyResponse) Descriptor() ([]byte, []int) {
	return file_pb_discopass_proto_rawDescGZIP(), []int{7}
}

func (x *BuyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuyResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *BuyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsuarioId     string                 `protobuf:"bytes,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	Monto         int32                  `protobuf:"varint,2,opt,name=monto,proto3" json:"monto,omitempty"`
	MedioPago     string                 `protobuf:"bytes,3,opt,name=medio_pago,json=medioPago,proto3" json:"medio_pago,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_pb_discopass_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discopass_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_pb_discopass_proto_rawDescGZIP(), []int{8}
}

func (x *PaymentRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *PaymentRequest) GetMonto() int32 {
	if x != nil {
		return x.Monto
	}
	return 0
}

func (x *PaymentRequest) GetMedioPago() string {
	if x != nil {
		return x.MedioPago
	}
	return ""
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_pb_discopass_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discopass_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_pb_discopass_proto_rawDescGZIP(), []int{9}
}

func (x *PaymentResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type DBWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBWriteRequest) Reset() {
	*x = DBWriteRequest{}
	mi := &file_pb_discopass_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBWriteRequest) ProtoMessage() {}

func (x *DBWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discopass_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBWriteRequest.ProtoReflect.Descriptor instead.
func (*DBWriteRequest) Descriptor() ([]byte, []int) {
	return file_pb_discopass_proto_rawDescGZIP(), []int{10}
}

func (x *DBWriteRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DBWriteRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DBWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBWriteResponse) Reset() {
	*x = DBWriteResponse{}
	mi := &file_pb_discopass_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBWriteResponse) ProtoMessage() {}

func (x *DBWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discopass_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBWriteResponse.ProtoReflect.Descriptor instead.
func (*DBWriteResponse) Descriptor() ([]byte, []int) {
	return file_pb_discopass_proto_rawDescGZIP(), []int{11}
}

func (x *DBWriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestorId   string                 `protobuf:"bytes,1,opt,name=requestor_id,json=requestorId,proto3" json:"requestor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_pb_discopass_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discopass_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_pb_discopass_proto_rawDescGZIP(), []int{12}
}

func (x *SyncRequest) GetRequestorId() string {
	if x != nil {
		return x.RequestorId
	}
	return ""
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string][]byte      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_pb_discopass_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discopass_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_pb_discopass_proto_rawDescGZIP(), []int{13}
}

func (x *SyncResponse) GetData() map[string][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// NUEVO: Mensajes para el Historial
type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsuarioId     string                 `protobuf:"bytes,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_pb_discopass_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discopass_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_pb_discopass_proto_rawDescGZIP(), []int{14}
}

func (x *HistoryRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

type TicketInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	EventoId      string                 `protobuf:"bytes,2,opt,name=evento_id,json=eventoId,proto3" json:"evento_id,omitempty"`
	NombreEvento  string                 `protobuf:"bytes,3,opt,name=nombre_evento,json=nombreEvento,proto3" json:"nombre_evento,omitempty"`
	FechaCompra   string                 `protobuf:"bytes,4,opt,name=fecha_compra,json=fechaCompra,proto3" json:"fecha_compra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketInfo) Reset() {
	*x = TicketInfo{}
	mi := &file_pb_discopass_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketInfo) ProtoMessage() {}

func (x *TicketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discopass_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketInfo.ProtoReflect.Descriptor instead.
func (*TicketInfo) Descriptor() ([]byte, []int) {
	return file_pb_discopass_proto_rawDescGZIP(), []int{15}
}

func (x *TicketInfo) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *TicketInfo) GetEventoId() string {
	if x != nil {
		return x.EventoId
	}
	return ""
}

func (x *TicketInfo) GetNombreEvento() string {
	if x != nil {
		return x.NombreEvento
	}
	return ""
}

func (x *TicketInfo) GetFechaCompra() string {
	if x != nil {
		return x.FechaCompra
	}
	return ""
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*TicketInfo          `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_pb_discopass_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discopass_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_pb_discopass_proto_rawDescGZIP(), []int{16}
}

func (x *HistoryResponse) GetTickets() []*TicketInfo {
	if x != nil {
		return x.Tickets
	}
	return nil
}

var File_pb_discopass_proto protoreflect.FileDescriptor

const file_pb_discopass_proto_rawDesc = "" +
	"\n" +
	"\x12pb/discopass.proto\x12\x02pb\"O\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9b\x02\n" +
	"\x05Event\x12\x1b\n" +
	"\tevento_id\x18\x01 \x01(\tR\beventoId\x12\x1c\n" +
	"\tdiscoteca\x18\x02 \x01(\tR\tdiscoteca\x12#\n" +
	"\rnombre_evento\x18\x03 \x01(\tR\fnombreEvento\x12\x1c\n" +
	"\tcategoria\x18\x04 \x01(\tR\tcategoria\x12\x16\n" +
	"\x06comuna\x18\x05 \x01(\tR\x06comuna\x12\x16\n" +
	"\x06precio\x18\x06 \x01(\x05R\x06precio\x12\x14\n" +
	"\x05stock\x18\a \x01(\x05R\x05stock\x12!\n" +
	"\ffecha_evento\x18\b \x01(\tR\vfechaEvento\x12+\n" +
	"\x11fecha_publicacion\x18\t \x01(\tR\x10fechaPublicacion\"G\n" +
	"\x0fPublishResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0e\n" +
	"\fEmptyRequest\".\n" +
	"\tEventList\x12!\n" +
	"\x06events\x18\x01 \x03(\v2\t.pb.EventR\x06events\"g\n" +
	"\n" +
	"BuyRequest\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x01 \x01(\tR\tusuarioId\x12\x1b\n" +
	"\tevento_id\x18\x02 \x01(\tR\beventoId\x12\x1d\n" +
	"\n" +
	"medio_pago\x18\x03 \x01(\tR\tmedioPago\"^\n" +
	"\vBuyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"d\n" +
	"\x0ePaymentRequest\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x01 \x01(\tR\tusuarioId\x12\x14\n" +
	"\x05monto\x18\x02 \x01(\x05R\x05monto\x12\x1d\n" +
	"\n" +
	"medio_pago\x18\x03 \x01(\tR\tmedioPago\"-\n" +
	"\x0fPaymentResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\">\n" +
	"\x0eDBWriteRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"+\n" +
	"\x0fDBWriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\vSyncRequest\x12!\n" +
	"\frequestor_id\x18\x01 \x01(\tR\vrequestorId\"w\n" +
	"\fSyncResponse\x12.\n" +
	"\x04data\x18\x01 \x03(\v2\x1a.pb.SyncResponse.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"/\n" +
	"\x0eHistoryRequest\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x01 \x01(\tR\tusuarioId\"\x8e\x01\n" +
	"\n" +
	"TicketInfo\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x1b\n" +
	"\tevento_id\x18\x02 \x01(\tR\beventoId\x12#\n" +
	"\rnombre_evento\x18\x03 \x01(\tR\fnombreEvento\x12!\n" +
	"\ffecha_compra\x18\x04 \x01(\tR\vfechaCompra\";\n" +
	"\x0fHistoryResponse\x12(\n" +
	"\atickets\x18\x01 \x03(\v2\x0e.pb.TicketInfoR\atickets2\x9c\x02\n" +
	"\rBrokerService\x12;\n" +
	"\x0eRegisterEntity\x12\x13.pb.RegisterRequest\x1a\x14.pb.RegisterResponse\x12.\n" +
	"\fPublishEvent\x12\t.pb.Event\x1a\x13.pb.PublishResponse\x125\n" +
	"\x12GetAvailableEvents\x12\x10.pb.EmptyRequest\x1a\r.pb.EventList\x12,\n" +
	"\tBuyTicket\x12\x0e.pb.BuyRequest\x1a\x0f.pb.BuyResponse\x129\n" +
	"\x0eGetUserHistory\x12\x12.pb.HistoryRequest\x1a\x13.pb.HistoryResponse2\xdd\x01\n" +
	"\x0fDatabaseService\x124\n" +
	"\tWriteData\x12\x12.pb.DBWriteRequest\x1a\x13.pb.DBWriteResponse\x12-\n" +
	"\bSyncData\x12\x0f.pb.SyncRequest\x1a\x10.pb.SyncResponse\x12-\n" +
	"\n" +
	"ReadEvents\x12\x10.pb.EmptyRequest\x1a\r.pb.EventList\x126\n" +
	"\vReadHistory\x12\x12.pb.HistoryRequest\x1a\x13.pb.HistoryResponse2H\n" +
	"\vBankService\x129\n" +
	"\x0eProcessPayment\x12\x12.pb.PaymentRequest\x1a\x13.pb.PaymentResponseB\x0eZ\fdiscopass/pbb\x06proto3"

var (
	file_pb_discopass_proto_rawDescOnce sync.Once
	file_pb_discopass_proto_rawDescData []byte
)

func file_pb_discopass_proto_rawDescGZIP() []byte {
	file_pb_discopass_proto_rawDescOnce.Do(func() {
		file_pb_discopass_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_discopass_proto_rawDesc), len(file_pb_discopass_proto_rawDesc)))
	})
	return file_pb_discopass_proto_rawDescData
}

var file_pb_discopass_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pb_discopass_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: pb.RegisterRequest
	(*RegisterResponse)(nil), // 1: pb.RegisterResponse
	(*Event)(nil),            // 2: pb.Event
	(*PublishResponse)(nil),  // 3: pb.PublishResponse
	(*EmptyRequest)(nil),     // 4: pb.EmptyRequest
	(*EventList)(nil),        // 5: pb.EventList
	(*BuyRequest)(nil),       // 6: pb.BuyRequest
	(*BuyResponse)(nil),      // 7: pb.BuyResponse
	(*PaymentRequest)(nil),   // 8: pb.PaymentRequest
	(*PaymentResponse)(nil),  // 9: pb.PaymentResponse
	(*DBWriteRequest)(nil),   // 10: pb.DBWriteRequest
	(*DBWriteResponse)(nil),  // 11: pb.DBWriteResponse
	(*SyncRequest)(nil),      // 12: pb.SyncRequest
	(*SyncResponse)(nil),     // 13: pb.SyncResponse
	(*HistoryRequest)(nil),   // 14: pb.HistoryRequest
	(*TicketInfo)(nil),       // 15: pb.TicketInfo
	(*HistoryResponse)(nil),  // 16: pb.HistoryResponse
	nil,                      // 17: pb.SyncResponse.DataEntry
}
var file_pb_discopass_proto_depIdxs = []int32{
	2,  // 0: pb.EventList.events:type_name -> pb.Event
	17, // 1: pb.SyncResponse.data:type_name -> pb.SyncResponse.DataEntry
	15, // 2: pb.HistoryResponse.tickets:type_name -> pb.TicketInfo
	0,  // 3: pb.BrokerService.RegisterEntity:input_type -> pb.RegisterRequest
	2,  // 4: pb.BrokerService.PublishEvent:input_type -> pb.Event
	4,  // 5: pb.BrokerService.GetAvailableEvents:input_type -> pb.EmptyRequest
	6,  // 6: pb.BrokerService.BuyTicket:input_type -> pb.BuyRequest
	14, // 7: pb.BrokerService.GetUserHistory:input_type -> pb.HistoryRequest
	10, // 8: pb.DatabaseService.WriteData:input_type -> pb.DBWriteRequest
	12, // 9: pb.DatabaseService.SyncData:input_type -> pb.SyncRequest
	4,  // 10: pb.DatabaseService.ReadEvents:input_type -> pb.EmptyRequest
	14, // 11: pb.DatabaseService.ReadHistory:input_type -> pb.HistoryRequest
	8,  // 12: pb.BankService.ProcessPayment:input_type -> pb.PaymentRequest
	1,  // 13: pb.BrokerService.RegisterEntity:output_type -> pb.RegisterResponse
	3,  // 14: pb.BrokerService.PublishEvent:output_type -> pb.PublishResponse
	5,  // 15: pb.BrokerService.GetAvailableEvents:output_type -> pb.EventList
	7,  // 16: pb.BrokerService.BuyTicket:output_type -> pb.BuyResponse
	16, // 17: pb.BrokerService.GetUserHistory:output_type -> pb.HistoryResponse
	11, // 18: pb.DatabaseService.WriteData:output_type -> pb.DBWriteResponse
	13, // 19: pb.DatabaseService.SyncData:output_type -> pb.SyncResponse
	5,  // 20: pb.DatabaseService.ReadEvents:output_type -> pb.EventList
	16, // 21: pb.DatabaseService.ReadHistory:output_type -> pb.HistoryResponse
	9,  // 22: pb.BankService.ProcessPayment:output_type -> pb.PaymentResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pb_discopass_proto_init() }
func file_pb_discopass_proto_init() {
	if File_pb_discopass_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_discopass_proto_rawDesc), len(file_pb_discopass_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_pb_discopass_proto_goTypes,
		DependencyIndexes: file_pb_discopass_proto_depIdxs,
		MessageInfos:      file_pb_discopass_proto_msgTypes,
	}.Build()
	File_pb_discopass_proto = out.File
	file_pb_discopass_proto_goTypes = nil
	file_pb_discopass_proto_depIdxs = nil
}
